name: Black

on:
  pull_request:
  push:
    branches: ["master"]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: psf/black@stable
        with:
          options: "--check --diff"
          src: "backend/src"
          version: "26.3.1"
