# Generated by Django 5.2 on 2026-03-01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('characters', '0014_add_harm_slot2_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='roll',
            name='rolled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rolls_made', to=settings.AUTH_USER_MODEL),
        ),
    ]
