# Generated by Django 5.2 on 2026-04-08 23:44

import characters.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0036_portrait_filefield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='stash_slots',
            field=models.JSONField(blank=True, default=characters.models._default_stash_slots, help_text='Personal stash grid when not in a crew (40 booleans). When crew is set, use Crew.stash_slots.'),
        ),
    ]
