# Generated by Django 5.2 on 2026-04-10 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0038_add_faction_shared_fields'),
        ('characters', '0038_npc_heritage_and_user_types'),
    ]

    operations = [
    ]
