# Generated by Django 5.2 on 2026-04-10 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0039_merge_20260410_1618'),
        ('characters', '0039_merge_20260410_1621'),
    ]

    operations = [
    ]
