# Generated by Django 5.2 on 2026-04-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0040_merge_20260410_1658"),
    ]

    operations = [
        migrations.AlterField(
            model_name="npc",
            name="relationships",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
