# Generated by Django 5.2 on 2026-04-10 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0040_merge_20260410_1729'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='faction',
            unique_together={('campaign', 'name')},
        ),
    ]
