# Generated by Django 5.2 on 2026-04-10 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0041_alter_npc_relationships"),
        ("characters", "0041_faction_unique_per_campaign"),
    ]

    operations = []
