# Generated by Django 5.2 on 2026-04-10 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0040_merge_20260410_1653'),
        ('characters', '0041_alter_npc_relationships'),
    ]

    operations = [
    ]
