# Generated by Django 5.2 on 2026-04-10 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0041_faction_unique_per_campaign'),
        ('characters', '0042_merge_20260410_1741'),
    ]

    operations = [
    ]
