# Generated by Django 5.2 on 2026-04-15 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0042_merge_20260410_2006'),
        ('characters', '0043_merge_20260410_1745'),
    ]

    operations = [
    ]
