# Generated by Django 5.2 on 2026-04-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0044_merge_20260415_2124"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avatar_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="External image URL for profile picture (no file upload).",
                max_length=500,
            ),
        ),
    ]
