# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0048_campaign_auditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="proposed_date",
            field=models.DateField(
                blank=True,
                help_text="Optional planned calendar date for this session.",
                null=True,
            ),
        ),
    ]
