# Generated by Django 5.2 on 2026-09-11 19:06

import uuid

import django.db.models.deletion
from django.db import migrations, models


def fold_inventory_notes_into_kit(apps, schema_editor):
    """Preserve free-text inventory_notes as a kit row so UI drop does not lose data."""
    NPC = apps.get_model("characters", "NPC")
    for npc in NPC.objects.exclude(inventory_notes="").iterator():
        notes = (npc.inventory_notes or "").strip()
        if not notes:
            continue
        inv = list(npc.inventory or []) if isinstance(npc.inventory, list) else []
        inv.append(
            {
                "id": str(uuid.uuid4()),
                "name": "Imported gear",
                "detail": notes,
                "category": "other",
                "load": 0,
                "quality": 1,
                "coin_value": None,
                "catalog_id": None,
                "is_armor": False,
                "armor_kind": "",
            }
        )
        npc.inventory = inv
        npc.inventory_notes = ""
        npc.save(update_fields=["inventory", "inventory_notes"])


def remove_gm_from_campaign_players(apps, schema_editor):
    """GMs are not players — drop them from the players M2M if previously added."""
    Campaign = apps.get_model("characters", "Campaign")
    Through = Campaign.players.through
    for campaign in Campaign.objects.exclude(gm_id=None).iterator():
        Through.objects.filter(
            campaign_id=campaign.id, user_id=campaign.gm_id
        ).delete()


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0113_sync_hamon_abilities_srd_dev"),
    ]

    operations = [
        migrations.AddField(
            model_name="npc",
            name="crew",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional player crew this NPC belongs to (independent of faction).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="npc_members",
                to="characters.crew",
            ),
        ),
        migrations.AddField(
            model_name="npc",
            name="crew_standing",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="This NPC's personal standing toward player crews (-3 to +3), keyed by crew id string.",
            ),
        ),
        migrations.RunPython(fold_inventory_notes_into_kit, noop_reverse),
        migrations.RunPython(remove_gm_from_campaign_players, noop_reverse),
    ]
