# Generated by Django 5.2 on 2026-09-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0113_sync_hamon_abilities_srd_dev'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='image',
            field=models.FileField(blank=True, help_text='Optional emblem or photo for this campaign.', null=True, upload_to='campaign_images/'),
        ),
    ]
