# Generated by Django 5.2 on 2026-09-11 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0114_campaign_image'),
        ('characters', '0114_npc_crew_and_crew_standing'),
    ]

    operations = [
    ]
