# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0116_chargen_baseline_respec"),
    ]

    operations = [
        migrations.AddField(
            model_name="faction",
            name="image_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Optional HTTPS URL for faction emblem (fallback when no uploaded file).",
                max_length=500,
            ),
        ),
    ]
