# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0117_faction_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="allow_character_assignment",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "When true, show the GM as a PLAYERS & CHARACTERS roster card "
                    "(including Create new / Assign existing when the GM has no "
                    "character). When false, hide that empty GM card. Player cards "
                    "are unchanged."
                ),
            ),
        ),
    ]
