# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0118_campaign_allow_character_assignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="faction",
            name="players_see_hold",
            field=models.BooleanField(
                default=True,
                help_text="When true (and visible_to_players), players may see faction hold.",
            ),
        ),
        migrations.AddField(
            model_name="faction",
            name="players_see_notes",
            field=models.BooleanField(
                default=True,
                help_text="When true (and visible_to_players), players may see faction notes.",
            ),
        ),
        migrations.AddField(
            model_name="faction",
            name="players_see_npcs",
            field=models.BooleanField(
                default=True,
                help_text="When true (and visible_to_players), players may see NPCs in this faction.",
            ),
        ),
        migrations.AddField(
            model_name="faction",
            name="players_see_reputation",
            field=models.BooleanField(
                default=True,
                help_text="When true (and visible_to_players), players may see faction reputation.",
            ),
        ),
        migrations.AddField(
            model_name="faction",
            name="players_see_tier",
            field=models.BooleanField(
                default=True,
                help_text="When true (and visible_to_players), players may see faction tier/level.",
            ),
        ),
    ]
