# Generated by Django 5.2 on 2026-09-30 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0121_npc_visible_to_players'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-session_date', '-id']},
        ),
    ]
